### ISSUE TITLE
Feature Request: Produce messages directly from the GUI

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#1055]
## Description
Often, to perform a quick message production, a standard solution would be to produce a message directly from the GUI without code.
For this feature, the following are required:

- [ ] Trigger an internal command of message production within the broker to a specific station without an external producer.
- [ ] Create a dedicated component within the GUI at the "Station overview" page, at the center panel, that will allow users to produce a message through the GUI. Ultimately, to enable tests for schemaverse, produce a message in four different formats: JSON, Protobuf, AVRO, GQL.

**Comment by Ciggzy1312** [comment]
@yanivbh1 I would like to work on this
A bit more description of the issue would be great for me to get started

**Comment by yanivbh1** [comment]
@Ciggzy1312 Done.
Thank you for your help!

**Comment by Ciggzy1312** [comment]
@yanivbh1 have some questions regarding the issue

Is there an endpoint through which the producer is sending the message to the station or do I have to create one (if yes can you point me to the code as I tried to find it but couldn't)
Also is there any specific design you want me to follow to create the GUI for message production directly using the client, like any Figma docs for reference or I can start working on it my way

**Comment by yanivbh1** [comment]
Hey @Ciggzy1312 ,
For the endpoint, no. It does not exist yet, and probably the biggest challenge in this task. To create one and internally trigger the produce functions.
A mock will be shared for the UI by the time the back is ready. Adding @avrhamNeeman 
Thank you!

**Comment by Ciggzy1312** [comment]
Hey @yanivbh1 I noticed NATS being used under the hood to publish the messages( correct me if I am wrong)
But I can't seem to find the produce functions that are sending the message to the station, if possible do point me to the code

Also the docs for running the rest gateway locally are not working, would appreciate help with that

**Comment by yanivbh1** [comment]
Hey @Ciggzy1312, adding @shay23b for the help.

**Comment by Avitaltrifsik** [comment]
Hey @Ciggzy1312 will be great if you could also join our [discord channel ](https://discord.gg/DfWFT7fzUu)

**Comment by shay23b** [comment]
Hi @Ciggzy1312 , we will review the best approach to implement this feature and will update ASAP
Regarding the rest gw please describe the issue you're experiencing, the best way is on our discord channel as Avital mentioned and we'll be happy to help

**Comment by idanasulinmemphis** [comment]
Hi @Ciggzy1312, as a start it will be better to create a new http POST endpoint /stations/produceMessage that will get headers + payload as parameters and will take care to send the message into the correct station + tenant. The UI part can be done once we will have the design

**Comment by yanivbh1** [comment]
Released on v1.2.
https://docs.memphis.dev/memphis/release-notes/releases/v1.2.0-latest
