### ISSUE TITLE
Schemaverse: Add support in Avro

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#1061]
## Adding support in Avro to Schemaverse

- [ ] GUI: Avro-oriented editor, syntax validation
- [ ] SDKs (across all client libraries): Serialization, deserialization, validation

**Comment by Big-Vi** [comment]
@yanivbh1 
I like to give this a go if you don't mind. It seems like a good issue to start contributing to memphis.

**Comment by yanivbh1** [comment]
Hey @Big-Vi ,
Great to have you with us!
Developing that feature will include the list I mentioned above. Lmk if it makes sense.

**Comment by Big-Vi** [comment]
https://github.com/memphisdev/memphis/pull/1107 PR is merged and it will be released on 1.1.2 version.
Major SDK's(Go, Python and JS) are supporting this feature for now.

**Comment by idanasulinmemphis** [comment]
Thanks @Big-Vi for your awesome contribution it will definitely help a lot to the Memphis community.
BTW .Net support is WIP as well.
