### ISSUE TITLE
Feature Request: Change message headers at any point in the message lifecycle

### ISSUE THREAD

**Issue by itay-grudev** [memphisdev/memphis#1077]
Imagine the following use case:

After a message has failed and you want retry / delay it with an exponential backoff. To do that you will need to record some state in the message that describes how many retry attempts there were so far, and maybe error information about why processing failed in the first place.

I suppose message headers are one way to achieve this, but currently message headers are only created when the message is produced and cannot be modified.

Allowing headers to be changed at any point during the lifetime of a message would allow some options to record message state, outside of the message body.

This means headers can be used for state as well as metadata.

Is this proposal technically feasible and are you interested in looking into it?

**Comment by yanivbh1** [comment]
Hey @itay-grudev ,
The nature of a queue is not to modify a message within the queue itself but rather to consume the message, modify it and then reproduce it to the station. Having said that, I wonder what is the use case behind it. Would love to learn. Tnx.

**Comment by itay-grudev** [comment]
### Scenario 1: API Limits

If you have a job that depends on an external API, if you burst said API limit your jobs will start failing.

So your system, reschedules those jobs to retry them. They get retried immediately (or after a small fixed delay), and continue to fail because of said API limit. In fact they are likely to make things worse. 

Jobs that fail get retried, the more you retry the bigger the API problem becomes.

### Scenario 1: A failed infrastructure component

When a certain infrastructure component has failed jobs using it will fail. Every failure is automatically retried 10 times by default creating back-pressure on the rest of the system components. Sudden increases in traffic due to the high retry-rate can cause a cascading failure leading to downtime of other components as well.

When the component is repaired, you want jobs to be re-ran automatically. In the classic scenario, jobs will remain in a DLS forever. With an exponential backoff, by the 10-th retry the component will have already been fixed.

---

In both cases the solution is to retry jobs with an exponential back-off: 

```
1s > 30s > 1m > 5m > 30m > 1h > 4h > 4h... 
```

But to implement that you have two options:

1. Create new jobs to replace old one, having the specified context, but this way CG that successfully processed the original message will process it again.
2. Adding state to existing messages. Which is my proposal.

**Comment by idanasulinmemphis** [comment]
Hi @itay-grudev sounds like a really cool feature but as @yanivbh1 said it is not the nature of such a system.
Not only this, think of it that each message can be consumed by more than 1 consumer group, which means that attaching errors to a specific message can cause other CGs (who didn't experience any issues with the message) to think that some errors occurred beforehand.
But I have another suggestion and I'd like to get your thoughts about it. We can add an indication regarding the amount of redeliveries, this numeric indication will be > 0 only for the affected CGs who experienced redeliveries events

**Comment by itay-grudev** [comment]
> But I have another suggestion and I'd like to get your thoughts about it. We can add an indication regarding the amount of redeliveries, this numeric indication will be > 0 only for the affected CGs who experienced redeliveries event.

That is a great idea and will solve the particular problem I am describing. I am really missing this meta information for messages in the API and I think it could be very useful.

**Comment by idanasulinmemphis** [comment]
@itay-grudev So please Open up a new feature request for getting message redeliveries count indication and I'll close this one
