### ISSUE TITLE
Bug: Incorrect email validation

### ISSUE THREAD

**Issue by itay-grudev** [memphisdev/memphis#1084]
### Describe the bug

The Memphis Cloud Email validation marks as invalid emails of the form:

```
user+something@example.com
user--something@example.com
```

You are likely performing email validation through an incorrect and extremely limiting Regex.
Email validation in general is extremely difficult. The most reliable email validation is sending an email and asking the user to confirm it through a link.

Consider:

1. Remove email validation completely
1. Simply validating for the presence of `@`.
2. Use the following **approximation** which should work about 99% of the time, recommended by the [W3C](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address):
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

### Steps to reproduce

1. Go to Users
2. Click "Add new user"
3. Fill in the user details
4. Use `user+something@example.com` as an email

Expected result: No error message
Actual result: Error message: `Please enter a valid email address!`

### Affected services

UI

### Broker version

Cloud

### If UI - Browsers

Firefox, Safari

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itay-grudev** [comment]
![image](https://github.com/memphisdev/memphis/assets/2123767/c98a0d7c-1367-4fae-b2a3-10ce99f595bf)

**Comment by yanivbh1** [comment]
Thank you for all the latest support @itay-grudev, highly appreciated!
Adding @idanasulinmemphis and @avrhamNeeman

**Comment by avrhamNeeman** [comment]
@itay-grudev Thanks for letting us know!
We will handle it by the coming release.

**Comment by idanasulinmemphis** [comment]
Hi @itay-grudev, I wanted to update you that we are not going to support "+" sign, inside emails since it is a door for users to sign up multiple times with the same email.
As it does not stand with our ISO/SOC2 compliance we decided to skip this.
Thanks.
