### ISSUE TITLE
Bug: user does not exist in db

### ISSUE THREAD

**Issue by AndryHTC** [memphisdev/memphis#1154]
### Describe the bug

Cannot use client accounts.
memphis -> `2023-07-19 17:41:28 [1] 2023/07/19 15:41:28.018024 [WRN] [tenant: $memphis][user: pontiscdcservice$1] createConsumerDirectCommon at GetUser from cache: user does not exist`

memphis .NET Client -> `Running processor on exception: user does not exist in db`

### Steps to reproduce

1. Run the Memphis Docker Image
2. Create station
3. Create user
4. Use the user with a .NET Client (maybe any client)
5. You get these errors

### Affected services

Broker, SDKs, Other

### Broker version

v1.1.1

### Platforms

Docker

### Environment

Development

### Additional context

Just updated from 1.1.0 that was working

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by idanasulinmemphis** [comment]
It is a known bug on 0.2.2 of the .NET SDK and we already released a new version, 0.2.3, containing a fix for that.
