### ISSUE TITLE
Feature: sqlite for meta data

### ISSUE THREAD

**Issue by gedw99** [memphisdev/memphis#1182]
### Current behavior

Running PostreSQL is a pain :)

Sure i can run CockroachDB, but then making that HA is not fun.

For cloud sure you can use the Supported cloud DB on GCP and AWS.

### Suggested solution

the postreSQL DB is great.

But using Pocktbase with sqlite and marmot gives a HA DB for very light deployments that are still HA.
No CGO too :)

https://github.com/maxpert/marmot uses NATS to keep the Sqlite DB consistent. SO its sort of aligned with memphis using nats :)

I know that you have written a ton of PostreSQL specific DTO code so i doubt this request will happen but well thats life.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Hey @gedw99 , 
Hope you are well. It's a good idea, but probably will be considered later this year.
Thanks.

**Comment by gedw99** [comment]
I got it working with cockroach cluster…

No changes needed

**Comment by gedw99** [comment]
will close this for now as the issue is no longer required.

Iceberg arrow is my preferred solution as I used S3 clustering g and gives higher multi core middle tier performance
