### ISSUE TITLE
Wrong module path prevents usage of memphis in embedded mode

### ISSUE THREAD

**Issue by g41797** [memphisdev/memphis#1252]
### Describe the bug

Current module-path (first line of go.mod)
```go
module memphis
```
It prevents usage of memphis code as regular package - required for embedded mode.

According to [go module-path](https://go.dev/ref/mod#glos-module-path) it should be
```go
module github.com/memphisdev/memphis
```

As far as I understand, change of go.mod is not enough, e.g.
```go
import (
	"memphis/analytics"
	"memphis/db"
	"memphis/http_server"
	"memphis/server"
)
```
should be changed to 
```go
import (
	"github.com/memphisdev/memphis/analytics"
	"github.com/memphisdev/memphis/db"
	"github.com/memphisdev/memphis/http_server"
	"github.com/memphisdev/memphis/server"
)
```

### Steps to reproduce

Try to use memphis in embedded mode

### Affected services

Broker

### Broker version

1.2.0

### Platforms

Other

### Environment

Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by idanasulinmemphis** [comment]
Hi @g41797 we will take care of it
