### ISSUE TITLE
Bug: Internal client should to use "MEMPHIS HTTP LOGGER" name for connection

### ISSUE THREAD

**Issue by g41797** [memphisdev/memphis#1264]
### Describe the bug

Internal client (syslog-adapter) can connect to broker only using "MEMPHIS HTTP LOGGER" name of rest-gateway (see working code below)
```go
	natsOpts := nats.Options{
		Url:            c.conf.MEMPHIS_HOST + ":6666",
		AllowReconnect: true,
		MaxReconnect:   10,
		ReconnectWait:  3 * time.Second,
		Name:           "MEMPHIS HTTP LOGGER",
		//Name:           "PROTOCOL-ADAPTER LOGGER",
	}


```

It's result of following new hard-coded check in the broker:
```go
				// *** added by Memphis
				if c.kind == CLIENT &&
					!strings.Contains(c.opts.Name, "NATS CLI") &&
					!c.isWebsocket() &&
					!strings.Contains(c.opts.Name, "MEMPHIS HTTP LOGGER") {
					if !s.validateAccIdInUsername(c.opts.Username) {
						goto accountIdErr
					}
				}
				// added by Memphis ***

```

### Steps to reproduce

Try to connect with different name

### Affected services

Broker

### Broker version

1.2.0

### Platforms

Other

### If UI - Browsers

Other (add additional context)

### Environment

Development

### Additional context

 Debugging on fedora38

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by g41797** [comment]
This connection is used for logging to broker - clone of rest-gateway implementation
Created logger is used by all blocks in the process

**Comment by idanasulinmemphis** [comment]
Is it should be the same logger connection for all protocols or is it one per protocol type?

**Comment by g41797** [comment]
Fan-in
Every protocol can create own logger
But all loggers of the process share the same Nats connection
I am going to save name in configuration
Later you can implement less hard-coded check of internal client name

**Comment by idanasulinmemphis** [comment]
Ok so for now leave the name as is
