### ISSUE TITLE
Feature: Add Memphis broker to Dapr

### ISSUE THREAD

**Issue by g41797** [memphisdev/memphis#1317]
### Description

[Dapr](https://dapr.io) already supports all  [well-known brokers](https://docs.dapr.io/reference/components-reference/supported-pubsub/)
It's time to add Memphis to this respected list

[Requirements for adding new broker](https://github.com/dapr/components-contrib/issues/3125#issuecomment-1718278181)

**Comment by yanivbh1** [comment]
Thank you for bringing it up @g41797 !

**Comment by g41797** [comment]
if the decision will be positive please assign it to me
