### ISSUE TITLE
Feature: Outbound Integrations

### ISSUE THREAD

**Issue by wahmedswl** [memphisdev/memphis#1377]
### Description

Hi!

Right now, Integrations seems to be Inbound where memphis is ingesting the data. Is there any possibility/integration where memphis is sending data to other services/components e.g. Kafka, MQTT etc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yanivbh1** [comment]
Hey @wahmedswl, not sure I understand the feature/request. Please explain more.

**Comment by wahmedswl** [comment]
@yanivbh1 Sorry that didn't make things clear. Is there any option available in memphis that it ingest data and then also send it to integrations. e.g. Kafka or MQTT etc.

Use case: We have EMQX broker that listens on MQTT and then forward that to memphis via rest-gateway. After it's ingested by memphis (station) then we want to forward it to Database or Kafka (due to multiple integrations). So technically, built-in integrations as consumers.

Thanks

**Comment by yanivbh1** [comment]
Understood @wahmedswl ,
So we call that "Connectors", and it will be available by the next release. Not v1.3.1, but rather 1.3.2 in two weeks from now.
https://github.com/memphisdev/memphis/issues/274
Please upvote so we would be able to notify you once out. Thanks!

**Comment by wahmedswl** [comment]
@yanivbh1 Thanks 👍
