### ISSUE TITLE
Feature: Create memphisphp repository

### ISSUE THREAD

**Issue by g41797** [memphisdev/memphis#1557]
### Description

memphisphp repo will contain php client for [memphisgrpc](https://github.com/g41797/memphisgrpc) part of [memphis-protocol-adapter](https://github.com/memphisdev/memphis-protocol-adapter)

### Additional context

#309

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by idanasulinmemphis** [comment]
Hi @g41797 this will be a community client library so you can manage it on your own account and we will mention that we have a PHP client library that backed by the community
