### ISSUE TITLE
Bug: No field to add password while creating user

### ISSUE THREAD

**Issue by Exar04** [memphisdev/memphis#1631]
### Describe the bug

<img width="1440" alt="Screenshot 2024-01-12 at 3 45 01 PM" src="https://github.com/memphisdev/memphis/assets/109629956/4bf87124-c60f-4c4e-a644-6732a0700801">
I was trying to create a user (producer) but password field is not visible.

### Steps to reproduce

1. go to stations
2. click on a station
3. click on "+" plus icon in producers
4. click on Develop a producer
5. click on select user
6. click on Create new user

### Affected services

UI

### Broker version

master 

### If UI - Browsers

Chrome, Safari

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by idanasulinmemphis** [comment]
@SvetaMemphis could you please take a look?

**Comment by idanasulinmemphis** [comment]
Hi @Exar04 in which way you are running the broker?

**Comment by Exar04** [comment]
Oh I was running memphis code (master branch) on my machine. I figure this might not be actual bug, But then how do I set password based auth?
Sorry if this was dumb.

**Comment by idanasulinmemphis** [comment]
@Exar04 Totally understood, it looks like you are not passing the USER_PASS_BASED_AUTH=true env var
