### ISSUE TITLE
DB and broker discrepancies are not handled

### ISSUE THREAD

**Issue by OrMemphis** [memphisdev/memphis#261]
When using Stations with the Memory storage type and with a single replica, if we kill the broker and start it again the Station(stream) will perish. although the DB still holds metadata as if the Station exists. 

**Expected behavior**
We should carefully design a solution here,
we can update the DB in this case, or not allow the Memory storage type at all...

**Comment by idanasulinmemphis** [comment]
Fixed on 0.4.4
