### ISSUE TITLE
Debezium HTTP-based integration

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#273]
## **Summary**
Enable connectivity between [Debezium](https://debezium.io/) to Memphis to enable CDC use cases.

## **Context**
Multiple streaming pipelines require support in CDC for different databases. Debezium gathers the most popular ones like MySQL, Postgre, and more in a single framework

## **Value**
Faster creation of CDC-based streaming pipelines

## **Persona(s)**
- DevOps
- Data Engineers
- Developers

## **Asked by**
- Yehuda Korotkin

Released on v1.1 and can be found on both the integration center and detailed here as well - https://memphis.dev/blog/part-1-integrating-debezium-server-and-memphis-dev-for-streaming-change-data-capture-cdc-events/

**Comment by yanivbh1** [comment]
https://github.com/debezium/debezium-server/pull/2#issuecomment-1409826434

**Comment by rnowling-memphis** [comment]
@yanivbh1 Can we close this as completed and notify the person who requested the feature?

**Comment by yanivbh1** [comment]
@rnowling-memphis Yes!
I will notify Yehuda personally, but would be great to mention the users who added upvotes.
@idanasulinmemphis can you please add it to your list for the upcoming release notes?

**Comment by yanivbh1** [comment]
Also adding @avrham @avrhamNeeman ,
Let’s add debezium to the integration center with a quick guide to make sure our users aware to it.

**Comment by avrhamNeeman** [comment]
@yanivbh1 @rnowling-memphis We're ready with a graphic of the Debezium integration. Please provide the relevant content.

**Comment by rnowling-memphis** [comment]
Edited the above to add the description for setting up the WAL level.
