### ISSUE TITLE
Inline processing

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#281]
## **Summary**
Embed functions and code in a serverless runtime into stations to enable stream processing on-the-fly.

## **Context**
One of Memphis's core features and milestones. Enabling true real-time stream processing within the broker itself using any language, any code made by the community, or users themselves instead of placing heavy business logic in the consumer/producer level. Stream processing usually takes place by stitching a broker with Apache Flink and similar apps, turning real-time to near real-time or slower. Memphis will provide a all three components under the same hood: Ingesting, transforming, and processing

## **Value**
True real-time, stream processing using any language, any type of code or app.

## **Persona(s)**
- Data Engineers
- Developers

**Comment by g41797** [comment]
"...Enabling true real-time stream processing **within the broker** itself .."
 does it mean that this processing should be done within memphis core server?
