### ISSUE TITLE
Scala SDK

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#290]

**Comment by sandeep540** [comment]
I think Java SDK - https://github.com/memphisdev/memphis-broker/issues/317 should be good, Scala can use the same, if there are 2 SDKs, it becomes twice as hard to maintain

same happened with Apache Flink (With 1.16 version , they deprecated all scala specific code)

**Comment by yanivbh1** [comment]
Thanks @sandeep540.
Closed.
