### ISSUE TITLE
Rust SDK

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#291]
## Update
Big thank you to @turulix and @ZargorNET for creating a community SDK for Rust.
https://github.com/turulix/memphis-rust-community

Currently, it supports consumption only, but we expect to support and enhance it soon.

## Requested by
@codifierr,@jeshwan,@dougg0k,@John0x,@boltomli,@amogower,@AbstractiveNord,@cortopy,@morigs,@Xorgentur,@loremaps,@spozdeev,@RemiKalbe,@joargp,@vincentserpoul,@George-Miao,@seryl,@ZargorNET,@nutrina,@shedrachokonofua,@thangchung,@jtoft-legion,@alon-david

**Comment by dougg0k** [comment]
Any ETA?

**Comment by yanivbh1** [comment]
Hey @dougg0k ,
Should be around the end of this year/beginning of the next one.
Highly requested by users

**Comment by alon-david** [comment]
Is it open to be taken?

**Comment by idanasulinmemphis** [comment]
Hi @alon-david yes this is all yours. 
In order to start, let's set up a kick off session. 
Have you already joined our Discord server?

**Comment by alon-david** [comment]
> Hi @alon-david yes this is all yours. In order to start, let's set up a kick off session. Have you already joined our Discord server?

yep `dalon` is the username :)

**Comment by yanivbh1** [comment]
Hey @alon-david ,
Would you like to restart this one and help attack it?

**Comment by yanivbh1** [comment]
Super happy to add this amazing contribution by @turulix!
https://github.com/turulix/memphis-rust-community
@Avitaltrifsik FYI!

**Comment by idanasulinmemphis** [comment]
That is huge

**Comment by dougg0k** [comment]
It says WIP not production ready yet, should that be disconsidered?

**Comment by yanivbh1** [comment]
Adding @turulix for the help

**Comment by turulix** [comment]
As of version 0.2.0 it should be good to use, just keep in mind that there might be breaking changes on minor newer Minor versions (We try to keep patch versions compatible). And some features are still WIP like the Schemaverse. But if you don't rely on those you should be good to go

**Comment by turulix** [comment]
Adding @ZargorNET cause he did a lot of the update

**Comment by yanivbh1** [comment]
Added to the credit.
Thank you, @ZargorNET!

**Comment by turulix** [comment]
> > Adding @ZargorNET cause he did a lot of the update
> 
> Will be great if you join our [discord](https://discord.gg/DfWFT7fzUu) as well @ZargorNET 

He is called Conner (@connerinbln) on discord
