### ISSUE TITLE
Java SDK

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#317]
https://github.com/memphisdev/memphis.java

**Comment by Jeerrryyyy** [comment]
Is there anything planned in the near future? Really a big fan of memphis and would love to use it in my java applications.

**Comment by yanivbh1** [comment]
Hey @Jeerrryyyy,
Thank you for your support! That's amazing.
.NET is coming up, and Java should be afterward.
Would you like to collaborate on this one together?

**Comment by yanivbh1** [comment]
Great!
I am working on a proper document specifically for building a new SDK,
but in the meantime -
1. Take [Go SDK](https://github.com/memphisdev/memphis.go) as an example that will help you a long the way
2. Make sure to implement each function
3. Pay close attention to consuming from the DLQ
4. Pay close attention to the schema flow which listening to new updates, cache update
5. There are two types of Ack for messages: standard and DLQ-based
6. Custom exceptions for the DLQ

It might be a lot to process, but it makes sense as you go, the entire team and maintainers are here to help,
and either way, great to have you with us!
Join us on [discord](https://memphis.dev/discord) as well

**Comment by yanivbh1** [comment]
Hey @Jeerrryyyy ,
Have you got the chance to start?

**Comment by Jeerrryyyy** [comment]
Hey @yanivbh1 ,
sorry for the late reply. No I did not had any chance yet because of some work load but I will probably start within the next week to initialize the project.

Do you have some preferences?
Something like:
- Java or Kotlin
- Gradle or Maven

**Comment by yanivbh1** [comment]
No worries.
@idanasulinmemphis, @elchinmemphis, and I thought about Java and Gradle.
What do you think about it @Jeerrryyyy?

Btw, In the coming days, we will share a document that explains in detail about building an SDK for memphis

**Comment by Jeerrryyyy** [comment]
Hey, I really think Gradle is a good choice too. If we go for Java here, we can maybe add some extension functions for kotlin later on to create a good developer experience. What do you guys think of this?

**Comment by yanivbh1** [comment]
Sounds good!

**Comment by sandeep540** [comment]
This will help in creating Apache Spark and Flink Connectors

**Comment by yanivbh1** [comment]
Hey @Jeerrryyyy,
did you get the chance to start?

**Comment by yanivbh1** [comment]
@sandeep540 would you like to work on this one together?

**Comment by sandeep540** [comment]
Sure will be happy to contribute,  thanks @yanivbh1

**Comment by Jeerrryyyy** [comment]
Hey @yanivbh1 , sorry like I said I had some pretty stressful weeks in december. Over christmas I wanted to have some time for myself and my girlfriend. I started and created a PR from my fork. I am on vacation the next week so I will have some time to work on the sdk. So I will continue with the first steps to create the project and setup a base structure. Do we have the .net sdk ready yet, because it should have similarities to the java sdk or?

**Comment by yanivbh1** [comment]
@Jeerrryyyy everything is great! Have a great time with your family! .NET SDK is in its final stages and can be found in memphis.net repo.
Maybe to share the workload, we can share the implementation with @sandeep540 by listing the plan. What do you think about it?
If it will be complicated that’s perfectly fine, and we can just leave specific features

**Comment by yanivbh1** [comment]
@Jeerrryyyy What a huge contribution!

**Comment by yanivbh1** [comment]
@sandeep540 @Jeerrryyyy Would be a huge help to wrap it together.
Any of you have the time or capacity to take the maintainer position over this one?
@Avitaltrifsik Please make sure you are set with swag packs. Thanks!

**Comment by Avitaltrifsik** [comment]
Hi @sandeep540 would be great to switch details on [discord](https://discord.gg/DfWFT7fzUu) so I can send you our cool swag :)

**Comment by sandeep540** [comment]
@Avitaltrifsik Joined Discord as sandeep540#3948

@yanivbh1 I just saw the scaffolding code , I was waiting for some instructions as to what to pick up?

**Comment by yanivbh1** [comment]
Hey @sandeep540,
Thanks for that.
Let's schedule a call? It would be great to have a short discussion and continue from there.
Sending my calendly link through Discord
