### ISSUE TITLE
Feature: SSE Server-sent events

### ISSUE THREAD

**Issue by gedw99** [memphisdev/memphis#345]
### Current behavior

The go sdk only supports golang. 

It would be highly useful if there was SSE support so that client systems can subscribe over SSE.
SSE is built into browsers, but can also be used by servers, mobile and desktop apps because SSE is just so simple.

It would make it very easy to consume off memphis system into any other system, in a real time reactive way.

### Suggested solution

https://github.com/alevinval/sse is a decent lib for it.

Here is an example of a system that supports SSE, to show off a use case
https://github.com/pocketbase/pocketbase/blob/0ac4c9e1fcb20bc8f92e5ae625e45b3d185ed3b4/core/app.go#L163
pocketbase is a simple firebase alternative in golang, that supports SSE so that apps built on top of it can get real time updates for whatever thing they are building. I only add this to show how useful SSE can be, as opposed to websockets which is much more complex.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
@gedw99, another great feature!
Go straight to this year's backlog.

**Comment by gedw99** [comment]
Thanks @yanivbh1 for adding me.

Would you comment on proposed design below.

The golang SDK Or the main server could provide the generic SSE functionality.   The intent is only to add a simple proxy so that the messages a user would receive over a nats consumer is received over a SSE connection. 
Because memphis wraps NATS, I presume then that the auth / authz to connect to and use a SSE connection will be done at the memphis level.

**Comment by idanasulinmemphis** [comment]
Hi @gedw99 this sounds like something which will best suite our connectors framework which will be released in the coming months.
How that sounds to you?

**Comment by gedw99** [comment]
> Hi @gedw99 this sounds like something which will best suite our connectors framework which will be released in the coming months. How that sounds to you?

@idanasulinmemphis Connector concept sounds like a nice approach. If there one yet. Would like to try out building the SSE connector.   

Also How will the NATS client based load balancing work. Memphis is wrapping NATS, so i am keen to see how Memphis will approach HA and scaling.

**Comment by idanasulinmemphis** [comment]
Connectors framework supposed to be implemented in the next release (v0.4.5) so we will let you know in the moment you can start implementing the SSE connector and we will be glad to get it from you.

Regarding your second question, Memphis took the concept of Jetstream pull consumer and out of it created a consumers group concept in order workloads will be splitted among all members in that group.

Regarding HA - as NATS, Memphis is RAFT based so your cluster is resilient as well as you don't have at least 1/2 cluster size + 1 operative nodes

**Comment by gedw99** [comment]
I ended up hooking up Pocketbase who has SSE with Memphis .

**Comment by gedw99** [comment]
> Connectors framework supposed to be implemented in the next release (v0.4.5) so we will let you know in the moment you can start implementing the SSE connector and we will be glad to get it from you.
> 
> Regarding your second question, Memphis took the concept of Jetstream pull consumer and out of it created a consumers group concept in order workloads will be splitted among all members in that group.
> 
> Regarding HA - as NATS, Memphis is RAFT based so your cluster is resilient as well as you don't have at least 1/2 cluster size + 1 operative nodes

It looks like it’s just using the nats clustering

**Comment by gedw99** [comment]
Also is no go db just being used to hold the data mapping that the users fill out in the gui ?

**Comment by idanasulinmemphis** [comment]
> > Connectors framework supposed to be implemented in the next release (v0.4.5) so we will let you know in the moment you can start implementing the SSE connector and we will be glad to get it from you.
> > Regarding your second question, Memphis took the concept of Jetstream pull consumer and out of it created a consumers group concept in order workloads will be splitted among all members in that group.
> > Regarding HA - as NATS, Memphis is RAFT based so your cluster is resilient as well as you don't have at least 1/2 cluster size + 1 operative nodes
> 
> It looks like it’s just using the nats clustering

+ memphis improvements for the inter-communication between brokers

**Comment by idanasulinmemphis** [comment]
> Also is no go db just being used to hold the data mapping that the users fill out in the gui ?

If you are asking about the mongo DB inside memphis deployment so yes only for application state not for storing data

**Comment by idanasulinmemphis** [comment]
> 
Great solution

**Comment by gedw99** [comment]
> > Also is no go db just being used to hold the data mapping that the users fill out in the gui ?
> 
> If you are asking about the mongo DB inside memphis deployment so yes only for application state not for storing data

Thanks 

you could have use SQLite lite with nats teplicstionnof the sql Wal using nats. That’s what marmot does . Scaling with no cgo and leveraging NATS for WAL reconciliation.
