### ISSUE TITLE
Expose memphis management API

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#628]
## Motivation
As developers, DevOps, and infrastructure engineers adopt GitOps and automation-oriented tools, it is crucial to enable users to manage Memphis via an API as well.

## Suggested Memphis implementation
Expose internal management endpoints to REST requests.

## Capabilities

- [ ] Create and manage schemaverse (asked by @damngamerz)

**Comment by Avitaltrifsik** [comment]
Hey @yanivbh1 could you please elaborate more on this iseeue?

Adding @abrl91

**Comment by yanivbh1** [comment]
Duplicate of #675
