### ISSUE TITLE
GUI-driven version upgrade

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#636]
## Motivation
As part of Memphis DevEx methodology, the need to operate on the infra-level should be narrowed to the minimum. That feature is to enable notification and upgrade of Memphis directly from the GUI

## Suggested Memphis implementation
Within the GUI, there should be an indicator for the new version where a model box will be open, list the new version release notes and in case of approval - interact with the underlying infrastructure and perform a rolling upgrade.

**Comment by avrhamNeeman** [comment]
Released in v1.0.0
