### ISSUE TITLE
Enrich documentation

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#637]
## More information
Enrich memphis documentations across the following sections
- https://docs.memphis.dev/memphis/getting-started/readme
- https://docs.memphis.dev/memphis/getting-started/2-hello-world
- https://docs.memphis.dev/memphis/memphis/architecture
- https://docs.memphis.dev/memphis/memphis/schemaverse-schema-management
- https://docs.memphis.dev/memphis/memphis/concepts/storage-and-redundancy
- https://docs.memphis.dev/memphis/memphis/concepts/consumer-groups

**Comment by WarpWing** [comment]
Just browsing through, I can help with some of this

**Comment by yanivbh1** [comment]
@WarpWing thanks.

**Comment by CodeJude** [comment]
I would like to work on this issue and contribute to the documentation.

**Comment by CodeJude** [comment]
> I would like to work on this issue and contribute to the documentation.

Made some Fixes I observe while going through the Docs [Fixed capitalization and omission of technology terms](https://github.com/memphisdev/gitbook-backup/pull/4)

**Comment by yanivbh1** [comment]
Thank you very much @CodeJude !

**Comment by CodeJude** [comment]
Thank you so much I appreciate @yanivbh1
