### ISSUE TITLE
Feature: Enhance GUI UX around integrations

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#762]
### Current behavior

- Successful integration setup close the integration model immedletly without pre sign or success message
- The current icon of a connected integration is not visible enough

### Suggested solution

- For a successful setup, there should be a much clearer indicator of success
- Icon of a connected integration should be different

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by avrhamNeeman** [comment]
Released
