### ISSUE TITLE
Feature: Improve SDK docs

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#763]
### Current behavior

Hard to understand how to set a value for retention type

### Suggested solution

Place another small headline for `retention value` below `retention type`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brunobandev** [comment]
Hi @yanivbh1 I can help with that, I searched for "retention" but I couldn't find anything about that in the sdk section. Could you provide me the URL? thank you

**Comment by brunobandev** [comment]
It's in the SDK documentation, I thought it was in the service documentation. Now I found it, I'll put it in the Golang SDK documentation and then add it to the others. Is that ok?

**Comment by yanivbh1** [comment]
Thanks @brunobandev .
Just to make sure, and before editing the files - can you please describe the change to make sure we are aligned and that I explained what is needed properly?

**Comment by brunobandev** [comment]
My understanding is to go through the sdk documentation and add in the readme information about `retention value` below `retention type` as shown in the image below.

![image](https://user-images.githubusercontent.com/31326787/221800061-cbaaa309-4ae6-4515-a324-af47a4025928.png)

Am I right? thank you

**Comment by yanivbh1** [comment]
Exactly @brunobandev !

**Comment by brunobandev** [comment]
@yanivbh1 I'll extend the doc update for the rest of the SDKs
