### ISSUE TITLE
Consumer prefetch

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#766]
Prefetching optimization to improve throughput.
Before returning a set of records to the user in consume(), the consumer will initiate the next round of fetches in order to pipeline the fetching overhead and message processing. While the consumer is processing the current batch of records, the broker can handle the consumer's fetch requests.
The idea is to have data available when the consumer finishes processing, invokes consume() again and gets a batch of messages.

## Status
The feature has been added to the Go SDK.

## Left to do
- [x] Python
- [ ] .NET
- [ ] Java
- [ ] JS

## Contributors
@devpahuja 
@yoelsherwin

**Comment by yoelsherwin** [comment]
Hi @yanivbh1, I'm new here and would like to try and take this on 😄 
Not sure I understood though - should this happen on the SDK side or the broker side?

**Comment by idanasulinmemphis** [comment]
Hi @yoelsherwin, it is on the SDK side.
In our Go,Python,Node.js SDKs we have a function called fetch_messages.
When it is called, it makes a fetch request to the broker. We want this function to have another boolean option called prefetch, in case it equals true, a pre-fetch request will be made into a local cache and the actual fetch messages made by the user will fetch directly from the cache instead of from the broker.

**Comment by yoelsherwin** [comment]
Hi @idanasulinmemphis, thanks! I'm starting with the Python SDK at the moment.
One more question: As far as I can tell, this requires introducing a local cache mechanism. Is that correct? Or am I missing an existing cache mechanism?

**Comment by yoelsherwin** [comment]
On second thought, I'll start with something simple

**Comment by yoelsherwin** [comment]
@idanasulinmemphis @yanivbh1 should the loading to cache be limited to the batch size? or do we want to pull even smaller batches?
I'm thinking about a case where we will be able to pull a part of the batch to the cache and then in the next `consume` the client will only need to pull the rest of the batch from the broker.

**Comment by yoelsherwin** [comment]
Hi @yanivbh1 , I already developed  the caching mechanism but I want to write some tests in-order to test it. 
@idanasulinmemphis Any thoughts on my question regarding the batch size? 🙂

**Comment by yanivbh1** [comment]
@Avitaltrifsik , Would be great to equip @yoelsherwin with a cool swag pack :)

**Comment by Avitaltrifsik** [comment]
Hey @yoelsherwin will be great if you can join our [discord channel](https://discord.gg/DfWFT7fzUu) so we can switch details to send you some of our cool swag :)

**Comment by idanasulinmemphis** [comment]
> 

We can create an internal buffer for pre-fetch requests, let's say, 2x the batch size.
New fetch requests will take messages from within this buffer.
@yoelsherwin What are you thinking about it?

**Comment by yoelsherwin** [comment]
I thought of that, but since `batch_size` can vary for every request, I think we should dynamically load `batch_size*2` messages into the internal buffer, and dynamically decide how many messages to pull from the buffer. Attaching a snippet:
```            if prefetch and self.cached_messages:
                if len(self.cached_messages) >= batch_size:
                    messages = self.cached_messages[:batch_size]
                    self.cached_messages = self.cached_messages[batch_size:]
                else:
                    pulled_messages_size = len(self.cached_messages)
                    messages = self.cached_messages
                    self.cached_messages = []
                    additional_messages = await consumer.fetch(batch_size - pulled_messages_size)
                    messages = messages + additional_messages
            else:
                messages = await consumer.fetch(batch_size)
            if prefetch:
                self.load_messages_to_cache(self, batch_size * 2, consumer)```
We should consider adding a configurable limit on cache size to avoid overloading the client's buffer. WDTY? @idanasulinmemphis

**Comment by yoelsherwin** [comment]
Hi, since there were some changes between SDK version 0.3.2 and the current master branch, I thought I share my PR here in the meantime to get your thoughts: https://github.com/memphisdev/memphis.py/pull/132
(For some reason I couldn't attach the PR to this issue)

**Comment by yanivbh1** [comment]
@idanasulinmemphis

**Comment by yanivbh1** [comment]
@idanasulinmemphis does @yoelsherwin need any help here?

**Comment by yoelsherwin** [comment]
Hi @yanivbh1, my PR is ready and waiting for a review :)

**Comment by yanivbh1** [comment]
Much appreciated @yoelsherwin !
Will be reviewed and merged soon. Thanks again for the contribution.

**Comment by yoelsherwin** [comment]
Hi @yanivbh1, I apologize for the delayed response, I've been quite busy with work. I'd be happy to try out the Java client!

**Comment by yanivbh1** [comment]
Hey @yoelsherwin, no worries!
Adding @rnowling-memphis, which leads the Java SDK.

**Comment by rnowling-memphis** [comment]
@yoelsherwin Thank you for your interest.  :) Can you take a look at the [Memphis.java](https://github.com/memphisdev/memphis.java) SDK code?  The consumer has very basic functionality right now -- it can only handle messages using a callback function. I'd like to get a sense of what would be needed to successfully implement prefetching.  Can you create an issue with your thoughts?  Thanks!
