### ISSUE TITLE
Bug: Code snippet model does not switch code samples between producer/consumer

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#770]
### Describe the bug

The code snippet model does not switch code samples between producer/consumer.
I checked in the sandbox.

### Steps to reproduce

1. Enter the station overview
2. Click on Code examples
3. Switch tabs between producer/consumer

### Affected services

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by avrhamNeeman** [comment]
Fixed
