### ISSUE TITLE
Bug: payload copy button not working

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#772]
### Describe the bug

<img width="291" alt="Screen Shot 2023-03-02 at 14 36 51" src="https://user-images.githubusercontent.com/70286779/222431408-9c11fdd8-40f8-4642-af37-5f743ca984b7.png">

### Steps to reproduce

UI

### Affected services

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by avrhamNeeman** [comment]
Fixed
