### ISSUE TITLE
Purge messages

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#793]
Ability to purge all of the messages stored in a station.

**Comment by idanasulinmemphis** [comment]
Hi @chirag0002, it is great to have you. This feature is almost ready and should be released in our next version (1.0.0).
But it would be great if you could take this one https://github.com/memphisdev/memphis/issues/579

**Comment by chirag0002** [comment]
Ok thanks @idanasulinmemphis, I'll take a look at this.

**Comment by yanivbh1** [comment]
Released on v1.0.0
