### ISSUE TITLE
Bug: Incorrect indentation in Python producer / consumer examples in UI

### ISSUE THREAD

**Issue by rnowling** [memphisdev/memphis#865]
### Describe the bug

As part of the UI getting started wizard, the wizard provides example code for producers and consumers.  The SDK examples for Python incorrectly independent one of the import statements:

```python
from __future__ import annotations
        import asyncio
from memphis import Memphis, MemphisError, MemphisConnectError, MemphisHeaderError
```

and 

```python
from __future__ import annotations
        import asyncio
from memphis import Memphis, Headers, MemphisError, MemphisConnectError, MemphisHeaderError, MemphisSchemaError
```

The independentation errors are coming from the code examples defined in [codeExample.js](https://github.com/memphisdev/memphis/tree/master/ui_src/src/const/codeExample.js), lines 251 and 274.

### Steps to reproduce

1. Start a new instance of Memphis.dev (I used the docker compose instructions)
2. Go to the UI in the web browser
3. Log in as root
4. You will be presented with a wizard for creating a station.
5. Perform step 1 (configure the station)
6. Perform step 2 (create an app user)
7. On step 3 (produce data), set the protocol to SDK and the language to Python -> see indentation error
8. On step 4 (consumer data), set the protocol to SDK and the language to Python -> see indentation error

### Affected services

UI

### Platforms

Docker

### If UI - Browsers

Firefox

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Thank you, @rnowling !
Adding @idanasulinmemphis for the review as well.

**Comment by idanasulinmemphis** [comment]
Thanks @rnowling, for reporting. @idonaaman123 will work on it and keep you updated.
