### ISSUE TITLE
Bug: bad REST Gateway code snippet

### ISSUE THREAD

**Issue by rnowling** [memphisdev/memphis#869]
### Describe the bug

As part of the UI getting started wizard, the wizard provides example code for producers and consumers.  The REST (HTTP) examples do not substitute the placeholders with the username and password, whereas the SDK examples do.  For example, this is a snippet of the Python code generated for the producer using the Python SDK:

```python
await memphis.connect(host="localhost", username="rnowling", password="ykp*HVM3gfq8vcp-czq")
```

whereas the snippet for the authentication REST call from Python does not have the username and password:

```python
payload = json.dumps({
  "username": "<application type username>",
  "password": "<password>",
  "token_expiry_in_minutes": 123,
  "refresh_token_expiry_in_minutes": 10000092
})
```

This does not appear to be a bug in the code constants but more likely a logic bug in [index.js](https://github.com/memphisdev/memphis/blob/master/ui_src/src/components/sdkExsample/index.js).

### Steps to reproduce

1. Start a new instance of Memphis.dev (I used the docker compose instructions)
2. Go to the UI in the web browser
3. Log in as root
4. You will be presented with a wizard for creating a station.
5. Perform step 1 (configure the station)
6. Perform step 2 (create an app user)
7. On step 3 (produce data), set the protocol to REST (HTTP) and any language -> see `<application type username>` and `<password>` in the authentication snippet
8. On step 4 (consumer data), set the protocol to REST (HTTP) and any language -> see `<application type username>` and `<password>` in the authentication snippet

### Affected services

UI

### Platforms

Docker

### If UI - Browsers

Firefox

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Thank you @rnowling .
Adding @avrham

**Comment by avrhamNeeman** [comment]
@rnowling Fixed, will be public in the next release.
