### ISSUE TITLE
Storage Tiering: Allow any S3 API compatible storage for remote/tier2

### ISSUE THREAD

**Issue by bjwschaap** [memphisdev/memphis#886]
### Current behavior

At this time only AWS S3 specifically is implemented. With minor adjustments it should be possible to support multiple S3 compatible storage backends 'out of the box'. With this feature other providers like Backblaze, e2, Digital Ocean Spaces, even Azure Blob storage (when using S3Proxy), or self-hosted alternatives like Minio.

### Suggested solution

- migrate AWS SDK Go to [v2](https://github.com/aws/aws-sdk-go-v2) ([docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2))
- Implement an [endpoint resolver](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/) that creates the correct s3 API endpoint based on Memphis Station configuration 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
@bjwschaap , that’s a great enhancement!
Definitely the right approach.
Would you like to contribute?

**Comment by bjwschaap** [comment]
I could take a crack at this one I think 😁

**Comment by yanivbh1** [comment]
> I could take a crack at this one I think

Perfect! Let’s do it. We are all here to support.

@idanasulinmemphis @Avitaltrifsik FYI

**Comment by idanasulinmemphis** [comment]
It sounds great, I love it. Please feel free to jump in and contribute what you offered.

**Comment by yanivbh1** [comment]
@bjwschaap does any help needed to kickstart?

**Comment by Avitaltrifsik** [comment]
Hey @bjwschaap would be great if you could join our [discord](https://discord.gg/DfWFT7fzUu) channel, we are available there 25/7 for any questions so as the Memphis community members :)

**Comment by bjwschaap** [comment]
I joined the Discord. @yanivbh1 it would be nice to have some docs or a quick introduction on how I can quickly setup a local dev environment and internal code organisation. I can already build and run, but tests are failing. I can figure it out own my own, but a little bit of guidance could get me up and running more quickly.

Also, I would like to split this new feature in a couple of tickets:

1. update AWS SDK to v2, keeping functionality the same
2. discuss on needed GUI changes for allowing custom S3 provider selection
3. implement GUI + DB changes for storing S3 endpoint url
4. Refactor current S3 implementation for (optionally) using S3 url

**Comment by idanasulinmemphis** [comment]
Sounds great, let’s keep chatting on Discord

**Comment by yanivbh1** [comment]
Hey @bjwschaap,
How is it going?

**Comment by bjwschaap** [comment]
First (partial) PR is coming up

**Comment by idanasulinmemphis** [comment]
This is huge, I'm on it

**Comment by yanivbh1** [comment]
Hey @idanasulinmemphis @bjwschaap , how is the PR going so far?
Can't wait to try it out!
