### ISSUE TITLE
Bug: REST code snippet

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#887]
### Describe the bug

Hey,
REST Code snippet does not format correctly, and when pasted within a terminal, it requires trimming and whitespace removals.

### Steps to reproduce

1. Station overview
2. Code snippets
3. REST
4. Copy&Paste token generation

### Affected services

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by idanasulinmemphis** [comment]
Done, will be released on 1.0.2
