### ISSUE TITLE
Bug: GUI text change

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#893]
### Describe the bug

![Screen Shot 2023-04-23 at 11 56 39](https://user-images.githubusercontent.com/70286779/233829991-c090fd5e-dace-4aa2-855a-5654b1e04038.png)

Attach to station -> Enforce a schema on a station
Attaching a scheme to a station will force the producers to follow it -> Enforcing a scheme on a station will force the producers to comply with it

### Steps to reproduce

1. Schemaverse
2. Edit exist schema
3. "Attach to station"

### Affected services

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by idanasulinmemphis** [comment]
Done, will be released on 1.0.2
