### ISSUE TITLE
Feature: GUI - Adding a label on all domain pages

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#906]
### Current behavior

Hey,
Currently, we don't have any links to the documentation within Schemaverse to get users started.

### Suggested solution

Add a label below the Schemaverse headline with the following text - 
"The new way to enforce schemas! Get started [here](https://docs.memphis.dev/memphis/memphis/schemaverse-schema-management/getting-started)
<img width="827" alt="Screen Shot 2023-04-25 at 11 06 19" src="https://user-images.githubusercontent.com/70286779/234215825-dd29e9c8-88a6-4644-98e3-c82cfa880928.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by avrhamNeeman** [comment]
@yanivbh1 Please provide relevant content for other pages:
Station
Users
Logs

**Comment by yanivbh1** [comment]
Stations page - "Stations stores events. More here" https://docs.memphis.dev/memphis/memphis/key-concepts/station
Users page - "For client authentication, choose "Application". For management only, choose "Management"
Logs - "Memphis platform system logs"

@avrhamNeeman

**Comment by avrhamNeeman** [comment]
@SvetaMemphis, Can you please add those descriptions to each domain page?

**Comment by SvetaMemphis** [comment]
@avrhamNeeman Sure
