### ISSUE TITLE
Feature: Ask the user to attach a schema right after its creation

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#908]
### Current behavior

Hey,
To push more users to attach schemas, we should always improve its UX and the users to the next stage.

### Suggested solution

My suggestion here is to pop up a question right after clicking "Create Schema" and passing validation with a question if the schema should be attached to a certain station

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Avitaltrifsik** [comment]
Hey @avrhamNeeman can a contributor take this one?

**Comment by avrhamNeeman** [comment]
@Avitaltrifsik Sure! I will provide mocks when he starts.

**Comment by rolwin100** [comment]
I want to take this up

**Comment by rolwin100** [comment]
@yanivbh1 can I have more context on this

**Comment by avrhamNeeman** [comment]
@rolwin100 When the user finishes creating a new schema, we need to pop a modal with the option to enforce the schema to certain stations before we direct him to the schemas page. (popup modal attached)
We've already implemented this popup on the schema details page, so you don't need to implement it from scratch.

We will provide the right content, but you can start working on it.
<img width="445" alt="Screenshot 2023-05-27 at 23 30 25" src="https://github.com/memphisdev/memphis/assets/74565114/7593a75c-2371-45f6-a9e6-5ee42843177f">

**Comment by rolwin100** [comment]
@avrhamNeeman will take this up ASAP thanks for the update

**Comment by rolwin100** [comment]
@avrhamNeeman I have created the PR for this task please check and let me know
