### ISSUE TITLE
Bug: Headers validation

### ISSUE THREAD

**Issue by yanivy-kela** [memphisdev/memphis#916]
### Describe the bug

There is no validation on header structure when i'm trying to produce message.
In nestjs, when i'm trying to consume a message i'm getting this error message:

"NatsError: ' ' is not a valid character for a header key".

### Steps to reproduce

1. Produce a message with header "test header".
2. Try to consume this message

### Affected services

SDKs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yanivbh1** [comment]
Thank you, @yanivy-kela!
It will be handled.

**Comment by idanasulinmemphis** [comment]
Hi @yanivy-kela, we have taken care of it on the SDK level. new SDK versions are available and containing this fix
