### ISSUE TITLE
Bug: Ui Mixes up Max Ack Time & Max Message Deliveries

### ISSUE THREAD

**Issue by turulix** [memphisdev/memphis#937]
### Describe the bug

![image](https://github.com/memphisdev/memphis/assets/28957605/4e8411e2-65b8-4e37-9238-b90a7c302a3b)

What it should look like:
![image](https://github.com/memphisdev/memphis/assets/28957605/f0886f4f-20a7-4c3d-807b-7d8c5f91e275)

### Steps to reproduce

Have a message in the Dead letters and display the Message journey

### Affected services

UI

### Platforms

Docker

### If UI - Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yanivbh1** [comment]
Thank you for opening this issue @turulix!
Will be fixed in the coming release.

**Comment by idanasulinmemphis** [comment]
Thanks @turulix. It got fixed over here https://github.com/memphisdev/memphis/pull/938
And will be released in our coming version
