### ISSUE TITLE
Clean up of redundant producers / consumers

### ISSUE THREAD

**Issue by JJWalsh** [memphisdev/memphis#941]
When calling destroy method on a producer or consumer object they remain listed in the GUI
The producer gets greyed out but the consumer just shows as offline

**Comment by yanivbh1** [comment]
Hey @JJWalsh ,
It's mainly for auditing, so you would have an understanding of what is happening or what happened within the station.
Having said that, we are working on a "garbage collector" that will be configured based on user-defined policy and will clean those out after a certain time threshold. #942 

I am closing this one out if there are no further issues.
