### ISSUE TITLE
Idempotency issues (.NET)

### ISSUE THREAD

**Issue by amitza** [memphisdev/memphis#945]
Hi! I'm new to Memphis and I have an issue understanding how to avoid consuming the same messages on consumer restart.
Scenario is simple: 1 producer 1 consumer and the retention limit of the station is 10,000 messages.
Using the .NET Memphis example I send 1000 messages and the consumer consumes them. After that I publish 1000 more messages and the consumer consumes 2000 messages. `IdempotenceWindowMs=0` and `MaxMsgDeliveries=1`.

One thing I've noticed is that I'm not able to create a station with 0 Idempotency, not using the GUI and not using the code.

image: `memphisos/memphis:stable` `a97180ee5c00e40a986a703f293c796cc5aac1be30b8223cd58693929ee036d9`

![2023-05-25_16-48-50](https://github.com/memphisdev/memphis/assets/9674751/83d068c4-efab-4c69-a39a-ea6c9b49231d)

```csharp
try
	{
		var options = MemphisClientFactory.GetDefaultOptions();
		options.Host = "localhost";
		options.Username = "sepio";
		options.Password = "sepio";
		var client = await MemphisClientFactory.CreateClient(options);

		var station = await client.CreateStation(
			stationOptions: new StationOptions()
			{
				Name = "test",
				RetentionType = RetentionTypes.MESSAGES,
				RetentionValue = 10000,
				StorageType = StorageTypes.MEMORY,
				Replicas = 1,
				IdempotenceWindowMs = 0
			});
		
		var producer = await client.CreateProducer(new MemphisProducerOptions
		{
			StationName = station.Name,
			ProducerName = "producer",
		});

		var consumer = await client.CreateConsumer(new MemphisConsumerOptions
		{
			StationName = station.Name,
			ConsumerName = "consumer",
			ConsumerGroup = "consumer-group",
			BatchSize = 1000,
			MaxMsgDeliveries = 1,
		});

		List<string> messages = new List<string>();

		consumer.MessageReceived += (sender, args) =>
		{
			if (args.Exception != null)
			{
				Console.Error.WriteLine(args.Exception);
				return;
			}
			foreach (var msg in args.MessageList)
			{
				//print message itself
				messages.Add(Encoding.UTF8.GetString(msg.GetData()));
				// print message headers
				foreach (var headerKey in msg.GetHeaders().Keys)
				{
					Console.WriteLine(
						$"Header Key: {headerKey}, value: {msg.GetHeaders()[headerKey.ToString()]}");
				}
				Console.WriteLine("---------");
				msg.Ack();
			}
		};

		consumer.ConsumeAsync();

		var commonHeaders = new NameValueCollection();
		commonHeaders.Add("key-1", "value-1");

		for (int i = 0; i < 1_000; i++)
		{
			var text = $"Message #{i}: Welcome to Memphis";
			await producer.ProduceAsync(Encoding.UTF8.GetBytes(text), commonHeaders, messageId: Guid.NewGuid().ToString());
		}

		await Task.Delay(5_000);
		await consumer.DestroyAsync();
		await producer.DestroyAsync();
		//await station.DestroyAsync();
	}
	catch (Exception ex)
	{
		Console.Error.WriteLine("Exception: " + ex.Message);
		Console.Error.WriteLine(ex);
	}
```

**Comment by yanivbh1** [comment]
Thank you for the issue @amitza and welcome to Memphis!
Adding @shay23b and @idanasulinmemphis for the rescue

**Comment by idanasulinmemphis** [comment]
Hi @amitz, Idempotency is relevant for the producer side, it drops messages with an identical msg ID, what means that if you are not sending your messages with msg ID idempotency is not in use, so no matter what appears on the time window field.

In regard what you asked about the re-consume of messages.
You are destroying your consumer before ending your app, meaning that the offset management destroyed as well, in case you want to start consuming from where you stopped, simply don’t destroy the consumer.

**Comment by amitz** [comment]
> Hi @amitz

Think you mean @amitza here and not @amitz ;-)
