### ISSUE TITLE
SysLog Error - [ERR] JetStream failed to store a msg on stream '$G >  

### ISSUE THREAD

**Issue by SvetaMemphis** [memphisdev/memphis#946]
Received the following error in the SysLog component:
`[ERR] JetStream failed to store a msg on stream '$G > $memphis_syslogs': error opening msg block file [\"/data/jetstream/$G/streams/$memphis_syslogs/msgs/1.blk\"]: open /data/jetstream/$G/streams/$memphis_syslogs/msgs/1.blk: read-only file system\n`

**Comment by idanasulinmemphis** [comment]
Hi @SvetaMemphi, it seems like this path on your pvc is restricted for read operations only, that means that Memohis can not write any message to the disk. I’d suggest to add permissions and then restart Memphis.
