### ISSUE TITLE
Feature Request: Bulk Resend of All Dead Letter Entries - GUI Only

### ISSUE THREAD

**Issue by ch3e3rs** [memphisdev/memphis#968]
### Current behavior

Yes, the current process of resending dead letter entries is manual and requires each entry to be selected individually.

### Suggested solution

I would like to see the introduction of a feature allowing users to resend all dead letter entries without having to manually select each one. This would involve a "select all" functionality for dead letter entries, followed by a bulk resend operation.

### Additional context

During a discussion in the Discord Memphis Message Broker forum, it was suggested that this feature might be available in an upcoming release (GUI in the coming release, programmatically in the next). I'm creating this request to formally track this feature and would appreciate being notified about its progress and release.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Thank you @ch3e3rs !
@idanasulinmemphis should be entered into v1.1.2 right?

**Comment by idanasulinmemphis** [comment]
Correct @yanivbh1

**Comment by ch3e3rs** [comment]
This is great, thank you all for your hard work!

**Comment by AndryHTC** [comment]
Any ETA for the 1.1.2? 😄

**Comment by yanivbh1** [comment]
@AndryHTC @ch3e3rs Aug 7.

**Comment by yanivbh1** [comment]
Hey @AndryHTC , @ch3e3rs , released on v1.2.
https://docs.memphis.dev/memphis/release-notes/releases/v1.2.0-latest
