### ISSUE TITLE
Bug: The Memphis application is not present in the Digital Ocean marketplace 

### ISSUE THREAD

**Issue by egatjens** [memphisdev/memphis#973]
### Describe the bug

I was trying to install the Memphis application on my Digital Ocean account following this [guide](https://docs.memphis.dev/memphis/deployment/cloud-deployment/deploy-on-digitalocean), but the application is not present in the marketplace 

### Steps to reproduce

1. Go to DO marketplace
2. Look for the Memphis app
3. Got "Oh no! We couldn't find the page you were looking for." on URL: https://marketplace.digitalocean.com/apps/memphis

### Affected services

Other

### Broker version

v1.0.2-stable

### Platforms

Kubernetes

### If UI - Browsers

Other (add additional context)

### Environment

Production

### Additional context

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yanivbh1** [comment]
Thanks for raising it @egatjens !
@valeraBr, where are we with the new deployment to DO? Should I ping them?

**Comment by valeraBr** [comment]
@yanivbh1 , the pull request was merged by DO yesterday night and the application was updated immediately. It's been in "In Review" status for the last 12 hours.

**Comment by yanivbh1** [comment]
Hey @egatjens ,
Please check now. It should be fixed.

**Comment by egatjens** [comment]
Yes, I can see the Memphis app on the DO market, thanks @valeraBr @yanivbh1
